query Collection($handle: String) {
  collection(handle: $handle) {
    handle
    products(first: 10) {
      edges {
        node {
          id
          images(first: 2) {
            edges {
              node {
                src
              }
            }
          }
          title
          description
          priceRange {
            minVariantPrice {
              amount
              currencyCode
            }
          }
          totalInventory
          handle
        }
      }
    }
  }
}
