query ProductByHandle($handle: String!) {
	productByHandle(handle: $handle) {
		id
		availableForSale
		title
		totalInventory
		images(first: 2) {
			edges {
				node {
					src
				}
			}
		}
		description
		productType
		priceRange {
			minVariantPrice {
				amount
				currencyCode
			}
		}
		options(first: 10) {
			name
			values
		}
	}
}
